### ISSUE TITLE
getting error on running main.js

### ISSUE THREAD

**Issue by noor927** [MrMagicPenguin/GLTF_Merger#1]
When i run npm main.js i get the following errors.

Unhandled rejection Error
    at new RuntimeError (/Users/noor/GLTF_Merger-master/node_modules/cesium/Build/CesiumUnminified/Cesium.js:6850:13)
    at finishLoading (/Users/noor/GLTF_Merger-master/node_modules/obj2gltf/lib/loadObj.js:462:15)
    at /Users/noor/GLTF_Merger-master/node_modules/obj2gltf/lib/loadObj.js:438:20
    at tryCatcher (/Users/noor/GLTF_Merger-master/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/noor/GLTF_Merger-master/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/noor/GLTF_Merger-master/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/noor/GLTF_Merger-master/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/noor/GLTF_Merger-master/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/noor/GLTF_Merger-master/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/noor/GLTF_Merger-master/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/noor/GLTF_Merger-master/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/noor/GLTF_Merger-master/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (node:internal/timers:463:21)

What am i doing wrong?

**Comment by noahprice-dev** [comment]
Let me take a look and see if it throws that issue on my end. I should add something stating this isn't a production ready solution, I never ended up using this tool after writing.

I can't really see where my tool comes in, this might be an issue either with Bluebird or Cesium though. Maybe I need to update those dependencies..

**Comment by noahprice-dev** [comment]
Depending on what you are doing, you might find more use in this tool while I tinker with mine, lol.
https://gltf-viewer.donmccurdy.com/
